import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {GraphQLClient , gql} from "graphql-request"
import BlogCard from "../components/BlogCard.js"
const graphcms = new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl98qjaqj1z6c01ue4arb2j33/master"
  
)
const QUERY = gql`
  {
    posts {
      id
      title
      dataPublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        
        url
      }
    }
  }
`;
export const getStaticProps = async() => {
  const {posts} = await graphcms.request(QUERY)
  return {
    props: {
      posts,
    },
    revalidate: 10,
    
  }
}
export default function Home(props) {
  const {posts} = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Dummy Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        {posts.map((post)=>(
          <BlogCard title = {post.title} author = {post.author} coverPhoto = {post.coverPhoto} key = {post.key} dataPublished = {post.dataPublished} slug={post.slug} />
        ))}
      </main>
      
    </div>
  )
}
